import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.lines = 45
dimensions.columns = 150
position.x = 270
position.y = 80

decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16
